import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    backgroundColor: "#2F2F2F",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
    height: "100%",
    paddingBottom: 10,
    marginBottom: 10,
  },
  button: {
    backgroundColor: "#F96800",
    paddingLeft: 25,
    paddingRight: 25,
    paddingTop: 2,
    paddingBottom: 5,
    borderRadius: 15,
    margin: 10,
    marginBottom: 30,
    shadowColor: "#000000",
    shadowOpacity: 0.7,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
  text: {
    fontSize: 18,
    color: "white",
    marginBottom: 15,
    position: "absolute",
    top: 10,
    zIndex: 5,
  },
  Btntext: {
    fontSize: 18,
    color: "white",
  },
  waiting: {
    backgroundColor: "#2F2F2F",
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    width: "100%",
    height: "100%",
  },

  title: {
    fontSize: 35,
    color: "white",
    marginBottom: 20,
    fontWeight: "600",
  },
  avatar: {
    height: 100,
    width: 100,
    borderRadius: 5,
  },
  pending: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  approved: {
    marginTop: 10,
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
  },
  pendingtext: {
    fontSize: 32,
    marginBottom: 30,
    color: "white",
    textAlign: "center",
  },
  username: {
    color: "white",
    fontSize: 16,
  },
  userCard: {
    alignItems: "center",
    justifyContent: "center",
    textAlign: "center",
    margin: 5,
  },
  ready: {
    height: 100,
    width: 100,
    padding: 5,
    borderWidth: 3,
    borderColor: "#008000",
    borderRadius: 15,
  },
  qrcontainer: {
    justifyContent: "center",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
  },
  waitingText: {
    color: "white",
    padding: 5,
    fontSize: 20,
  },
  logo: {
    width: "85%",
    resizeMode: "contain",
    marginTop: 0,
    flex: 1,
  },
  waitingMessage: {
    flex: 1,
    marginBottom: 15,
    width: "85%",
  },
  groupidtext: {
    color: "white",
    textAlign: "center",
    padding: 20,
  },
  tripButton: {
    backgroundColor: "#F96800",
    paddingLeft: 25,
    paddingRight: 25,
    paddingTop: 2,
    paddingBottom: 5,
    borderRadius: 15,
    margin: 10,
    marginBottom: 30,
    shadowColor: "#000000",
    width: "50%",
    marginLeft: 90,
    alignItems: "center",
    shadowOpacity: 0.7,
    shadowRadius: 2,
    shadowOffset: {
      height: 1,
      width: 1,
    },
  },
  scrollview: {
    width: "100%",
  },
  bubble: {
    flexDirection: "column",
    alignSelf: "flex-start",
    backgroundColor: "#E3E3E3",
    borderRadius: 6,
    borderColor: "#F96800",
    borderWidth: 0.5,
    padding: 15,
    width: 150,
  },
  bubbleText: {
    paddingBottom: 5,
    padding: 10,
  },
  bubbleBtn: {
    backgroundColor: "#F96800",
    borderRadius: 6,
    borderColor: "#2F2F2F",
    padding: 2,
  },
  calloutImage: {
    width: 5,
    height: 5,
    resizeMode: "stretch",
  },
});
